# Generated by Django 4.1.2 on 2022-12-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the post", max_length=255
                    ),
                ),
                ("post", models.TextField(help_text="Enter your post content")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of the post",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "blog_post",
                "verbose_name_plural": "blog_posts",
                "default_related_name": "blog_posts",
                "order_with_respect_to": "title",
            },
        ),
    ]
